# Data Exploration: SPEED Dataset

This notebook explores the SPEED dataset and its codebook to:
1. Understand the data structure
2. Explore data definitions from the codebook
3. Take sample rows from the data
4. Resolve enum values to their true meanings

In [32]:
import pandas as pd
import numpy as np
from pathlib import Path

# Set display options for better viewing
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', 50)

# File paths
data_dir = Path('data')
codebook_file = data_dir / 'SPEED-Codebook.xls'
data_file = data_dir / 'ssp_public.xls'

print(f"Codebook file exists: {codebook_file.exists()}")
print(f"Data file exists: {data_file.exists()}")

Codebook file exists: True
Data file exists: True

## 1. Load and Explore Codebook

In [33]:
# Read the codebook - Excel files may have multiple sheets
codebook_excel = pd.ExcelFile(codebook_file)
print(f"Codebook sheets: {codebook_excel.sheet_names}")

# Load all sheets from codebook
codebook_sheets = {}
for sheet_name in codebook_excel.sheet_names:
    codebook_sheets[sheet_name] = pd.read_excel(codebook_file, sheet_name=sheet_name)
   # print(f"\nSheet '{sheet_name}' shape: {codebook_sheets[sheet_name].shape}")
   # print(f"Columns: {list(codebook_sheets[sheet_name].columns)}")
    #display(codebook_sheets[sheet_name].head())

codebook_sheets

Codebook sheets: ['Variable Description', 'Value Labels', 'Notes']

{'Variable Description':              Variable                     Variable Description
 0             eventid              Event identification number
 1             country      Country in which the event occurred
 2             cowcode  Cowcode of country where event occurred
 3           ini_igrp1        Name of insurgent group initiator
 4           tar_igrp1           Name of insurgent group target
 ..                ...                                      ...
 100            region     Eight category world region variable
 101     victim_effect                Impact of event on victim
 102            weapon                      Type of weapon used
 103  property_damaged                 Type of property damaged
 104    property_owner       Type of owner for damaged property

 [105 rows x 2 columns],
 'Value Labels':      Variable            Variable Labels
 0     ev_type                0="Missing"
 1         NaN   1="Political Expression"
 2         NaN      2="Political Attacks"
 3         NaN                    3= NULL
 4         NaN  4="Disruptive State Acts"
 ..        ...                        ...
 411       NaN                        NaN
 412  e_length                1='One Day'
 413       NaN      2='Two to Seven Days'
 414       NaN    3='One Week to a Month'
 415       NaN   4='Greater than a Month'

 [416 rows x 2 columns],
 'Notes': Empty DataFrame
 Columns: [1., A previous version of this document listed the variable n_injurd_d as a discrete variable.  This is incorrect.  Instead this variable is a count variable, similar to variable n_injurd.  It only differs from n_injurd in that n_injurd_d has a maximum value of 10, while n_injurd has no maximum value. ( 11/6/2014)]
 Index: []}

## 2. Load and Explore Main Data

In [34]:
# Read the main data file
data_excel = pd.ExcelFile(data_file)
print(f"Data file sheets: {data_excel.sheet_names}")

# Load the main data (assuming first sheet or 'Sheet1')
if len(data_excel.sheet_names) > 0:
    main_sheet = data_excel.sheet_names[0]
    df = pd.read_excel(data_file, sheet_name=main_sheet)
    
    print(f"\nData shape: {df.shape}")
    print(f"Columns ({len(df.columns)}): {list(df.columns)}")
    print(f"\nData types:")
    print(df.dtypes)
    print(f"\nMissing values:")
    print(df.isnull().sum())
    
    display(df.head(10))

Data file sheets: ['ssp_public']

Data shape: (62141, 106)
Columns (106): ['cowcode', 'month', 'year', 'eventid', 'country', 'INI_IGRP1', 'TAR_IGRP1', 'VIC_IGRP1', 'INI_SGRP1', 'TAR_SGRP1', 'VIC_SGRP1', 'INI_PGRP1', 'TAR_PGRP1', 'VIC_PGRP1', 'KNOW_INI', 'AMBIG_INI', 'INI_TYPE', 'NGOV_I1', 'GOV_I1', 'TAR_TYPE', 'HUMAN_T1', 'GOV_T1', 'G_LVL_I', 'G_LVL_T', 'G_LVL_V', 'HUMAN_V1', 'GOV_V1', 'VIC_TYPE', 'DATE_TYP', 'day', 'JUL_PSD', 'JUL_PED', 'JUL_EED', 'JUL_LED', 'JUL_START_DATE', 'JUL_END_DATE', 'DAY_SPAN', 'N_INJURD', 'TAR_GPOL', 'GP_TYPE', 'aid', 'PUB_MON', 'PUB_DATE', 'PUB_YEAR', 'recap', 'NEWS_SOURCE', 'CODE_YEAR', 'CODE_MONTH', 'CODE_DAY', 'event', 'posthoc', 'EV_TYPE', 'linked', 'LINK_TYPE', 'FROM_EID', 'TO_EID', 'pinpoint', 'GP3', 'GP4', 'GP7', 'GP8', 'LOC_TYPE', 'PE_TYPE', 'SYM_TYPE', 'AD_VIOL', 'AD_TACT', 'EXP_TYPE', 'ATK_TYPE', 'DSA_TYPE', 'STAT_ACT', 'N_OF_INI_P', 'N_OF_INI_A', 'WEAP_GRD', 'N_KILLED_P', 'N_KILLED_A', 'E_LENGTH', 'N_INJURD_D', 'DAM_PROP', 'arrests', 'PER_ATK_I', 'PER_ATK_E', 'PUB_ORDER', 'retribution', 'POL_EXPRESS', 'INTANG_REP', 'MASS_EXPRESS', 'POL_VIOL', 'STAT_VIOL', 'ST_REPRESS', 'AMBIG_WGT', 'SC_ANIMOSITY', 'ANTI_GOV_SENTMNTS', 'CLASS_CONFLICT', 'POL_DESIRES', 'RETAIN_POWER', 'ECO_SCARCITY', 'PERS_SECURITY', 'QUASI_EVENT', 'coup', 'COUP_FAILED', 'region', 'ctry_bias', 'victim_effect', 'weapon', 'property_damaged', 'property_owner']

Data types:
cowcode             float64
month               float64
year                  int64
eventid              object
country              object
                     ...
ctry_bias           float64
victim_effect       float64
weapon                int64
property_damaged    float64
property_owner      float64
Length: 106, dtype: object

Missing values:
cowcode               236
month                  67
year                    0
eventid                 0
country               436
                    ...
ctry_bias             436
victim_effect       17538
weapon                  0
property_damaged    61277
property_owner      54068
Length: 106, dtype: int64

,cowcode,month,year,eventid,country,INI_IGRP1,TAR_IGRP1,VIC_IGRP1,INI_SGRP1,TAR_SGRP1,VIC_SGRP1,INI_PGRP1,TAR_PGRP1,VIC_PGRP1,KNOW_INI,AMBIG_INI,INI_TYPE,NGOV_I1,GOV_I1,TAR_TYPE,HUMAN_T1,GOV_T1,G_LVL_I,G_LVL_T,G_LVL_V,HUMAN_V1,GOV_V1,VIC_TYPE,DATE_TYP,day,JUL_PSD,JUL_PED,JUL_EED,JUL_LED,JUL_START_DATE,JUL_END_DATE,DAY_SPAN,N_INJURD,TAR_GPOL,GP_TYPE,aid,PUB_MON,PUB_DATE,PUB_YEAR,recap,NEWS_SOURCE,CODE_YEAR,CODE_MONTH,CODE_DAY,event,posthoc,EV_TYPE,linked,LINK_TYPE,FROM_EID,TO_EID,pinpoint,GP3,GP4,GP7,GP8,LOC_TYPE,PE_TYPE,SYM_TYPE,AD_VIOL,AD_TACT,EXP_TYPE,ATK_TYPE,DSA_TYPE,STAT_ACT,N_OF_INI_P,N_OF_INI_A,WEAP_GRD,N_KILLED_P,N_KILLED_A,E_LENGTH,N_INJURD_D,DAM_PROP,arrests,PER_ATK_I,PER_ATK_E,PUB_ORDER,retribution,POL_EXPRESS,INTANG_REP,MASS_EXPRESS,POL_VIOL,STAT_VIOL,ST_REPRESS,AMBIG_WGT,SC_ANIMOSITY,ANTI_GOV_SENTMNTS,CLASS_CONFLICT,POL_DESIRES,RETAIN_POWER,ECO_SCARCITY,PERS_SECURITY,QUASI_EVENT,coup,COUP_FAILED,region,ctry_bias,victim_effect,weapon,property_damaged,property_owner
0,NaN,NaN,1946,EID40124,NaN,.,.,.,.,.,.,.,.,.,1.0,0,1.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,593.0,593.0,593.0,593.0,NaN,NaN,NaN,0,0,NaN,19194629.0,8,17,1946,0,NYT,2009,4,18,1,0,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,4.0,NaN,0,17.0,1.0,NaN,NaN,NaN,1.0,1.0,1.0,0.0,0,1,0,0,0,0,0,0,0,1.0,NaN,NaN,NaN,NaN,NaN,0.0,0,0,1,0,0,0,0,0,0,0,NaN,NaN,1.0,1,NaN,NaN
1,NaN,NaN,1946,EID51193,NaN,.,.,.,.,.,.,.,.,.,1.0,0,2.0,NaN,3.0,3.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,398.0,398.0,NaN,NaN,NaN,NaN,NaN,0,1,5.0,2159468.0,2,3,1946,0,NYT,2009,6,24,1,0,1.0,1,0.0,EID51193,EID51194,2.0,NaN,NaN,NaN,NaN,22.0,8.0,NaN,0,17.0,4.0,NaN,NaN,NaN,NaN,30.0,1.0,0.0,0,1,0,0,0,0,0,0,0,NaN,NaN,1.0,NaN,NaN,NaN,0.0,0,0,1,0,0,0,0,0,0,0,NaN,NaN,NaN,1,NaN,NaN
2,NaN,11.0,1948,EID133296,NaN,.,.,.,.,.,.,Association Of Catholic Trade Unionists,.,.,1.0,0,1.0,6.0,NaN,1.0,37.0,10.0,NaN,3.0,3.0,37.0,10.0,NaN,1.0,15.0,1415.0,1415.0,NaN,NaN,1415.0,1415.0,1.0,0,0,NaN,19354824.0,11,16,1948,0,NYT,2010,4,11,1,0,1.0,0,NaN,NaN,NaN,3.0,FALKLAND ISLANDS (ISLAS MALVINAS),FALKLAND ISLANDS (ISLAS MALVINAS),-51.750000,-59.000000,2.0,7.0,NaN,0,17.0,4.0,NaN,NaN,NaN,NaN,1250.0,1.0,0.0,0,1,0,0,0,0,0,0,0,NaN,NaN,1.1,NaN,NaN,NaN,0.0,1,1,1,0,0,0,0,0,0,0,NaN,NaN,13.0,1,NaN,NaN
3,NaN,9.0,1951,EID102797,NaN,.,.,.,.,.,.,.,.,.,1.0,0,1.0,5.0,NaN,1.0,37.0,18.0,NaN,3.0,3.0,37.0,18.0,NaN,1.0,8.0,2442.0,2442.0,NaN,NaN,2442.0,2442.0,1.0,0,0,NaN,19669349.0,9,9,1951,0,NYT,2010,1,29,1,0,1.0,0,NaN,NaN,NaN,3.0,JERSEY,JERSEY,49.216702,-2.116670,2.0,9.0,15.0,0,17.0,2.0,NaN,NaN,NaN,NaN,7.0,2.0,0.0,0,1,0,0,0,0,0,0,0,1.9,NaN,NaN,NaN,NaN,NaN,0.0,0,1,0,0,0,0,0,0,0,0,NaN,NaN,13.0,13,NaN,NaN
4,NaN,7.0,1952,EID257135,NaN,.,.,.,.,.,.,.,.,.,2.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,30.0,2768.0,2768.0,NaN,NaN,2768.0,2768.0,1.0,0,0,NaN,19881693.0,7,31,1952,0,NYT,2011,6,1,1,0,2.0,0,NaN,NaN,NaN,3.0,MACAU,MACAO,22.200600,113.545998,2.0,NaN,NaN,0,NaN,NaN,6.0,NaN,NaN,NaN,NaN,1.0,0.0,0,1,0,0,0,1,0,0,0,NaN,NaN,NaN,2.8,NaN,NaN,0.5,0,0,0,0,0,0,0,0,0,0,NaN,NaN,13.0,1,NaN,NaN
5,NaN,11.0,1952,EID47103,NaN,.,.,.,.,.,.,.,.,.,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,14.0,2875.0,2875.0,2877.0,2877.0,2875.0,2875.0,1.0,0,0,NaN,19859970.0,11,17,1952,0,NYT,2009,5,15,1,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0,1,0,1,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,41.0,NaN
6,NaN,2.0,1953,EID318983,NaN,.,.,.,.,Argentine,.,.,.,.,1.0,0,2.0,NaN,3.0,2.0,37.0,20.0,3.0,3.0,3.0,37.0,20.0,NaN,1.0,19.0,2972.0,2972.0,NaN,NaN,2972.0,2972.0,1.0,0,0,NaN,2188221.0,2,20,1953,0,NYT,2012,5,8,1,0,4.0,0,NaN,NaN,NaN,3.0,antarctica,antarctica,-85.622101,32.343800,2.0,NaN,NaN,0,NaN,NaN,6.0,4.0,41.0,NaN,NaN,3.0,0.0,0,1,0,0,1,1,0,0,0,NaN,NaN,NaN,NaN,3.6,NaN,0.0,1,0,0,1,1,0,0,0,0,0,NaN,NaN,4.0,14,NaN,12.0
7,NaN,5.0,1953,EID47389,NaN,.,.,.,.,.,.,.,.,.,1.0,0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,2.0,10.0,3051.0,3052.0,3053.0,3053.0,3051.0,3052.0,2.0,0,0,NaN,20001541.0,5,12,1953,0,NYT,2009,5,16,1,0,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0,2,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,0,0,0,0,0,0,0,0,0,NaN,NaN,NaN,1,NaN,NaN
8,NaN,12.0,1953,EID49541,NaN,.,.,.,.,.,.,.,.,.,0.0,0,NaN,NaN,3.0,1.0,29.0,NaN,3.0,NaN,NaN,29.0,NaN,NaN,1.0,28.0,3284.0,3284.0,2923.0,3284.0,3284.0,3284.0,1.0,0,0,NaN,19913935.0,12,29,1953,0,NYT,2009,6,8,1,1,2.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,0,NaN,NaN,8.0,NaN,NaN,NaN,30.0,3.0,1.0,1,1,0,0,0,1,0,0,0,NaN,NaN,NaN,2.8,NaN,NaN,0.0,0,1,0,0,0,0,0,0,0,0,NaN,NaN,12.0,14,NaN,NaN
9,NaN,12.0,1953,EID49542,NaN,.,.,.,Jordanian,.,.,.,.,.,1.0,0,1.0,1.0,NaN,1.0,29.0,NaN,NaN,NaN,NaN,29.0,NaN,NaN,1.0,28.0,3284.0,3284.0,NaN,NaN,3284.0,3284.0,1.0,1,0,NaN,19913935.0,12,29,1953,0,NYT,2009,6,8,1,0,2.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,0,NaN,NaN,8.0,NaN,NaN,NaN,400.0,3.0,0.0,0,1,1,0,0,1,0,0,0,NaN,NaN,NaN,2.8,NaN,NaN,0.0,1,1,0,0,0,0,0,0,0,0,NaN,NaN,10.0,14,NaN,NaN

## 3. Understand Codebook Structure and Create Mapping Dictionary

In [45]:
# Function to create enum mapping from codebook
def create_enum_mapping(codebook_sheets):
    """
    Create a dictionary mapping column names to their descriptions and enum values.
    
    Structure:
    {
        column_name: {
            "description": "...",
            "enums": {
                "key": "value",
                ...
            }
        }
    }
    
    Reads from:
    - "Variable Description" sheet: Variable -> Variable Description
    - "Value Labels" sheet: Variable (when not NaN) indicates variable name,
                            Variable Labels contains enum definitions like '0="Missing"'
    """
    import re
    
    enum_mappings = {}
    
    # Step 1: Read Variable Description sheet to get descriptions
    var_desc_sheet = codebook_sheets.get('Variable Description')
    descriptions = {}
    
    if var_desc_sheet is not None:
        # Find the column names
        var_col = None
        desc_col = None
        for col in var_desc_sheet.columns:
            col_lower = str(col).lower()
            if 'variable' in col_lower and 'description' not in col_lower:
                var_col = col
            elif 'description' in col_lower:
                desc_col = col
        
        if var_col and desc_col:
            for _, row in var_desc_sheet.iterrows():
                var_name = row[var_col]
                desc = row[desc_col]
                if pd.notna(var_name) and pd.notna(desc):
                    var_name = str(var_name).strip().lower()
                    descriptions[var_name] = str(desc).strip()
    
    # Step 2: Read Value Labels sheet to get enum mappings
    value_labels_sheet = codebook_sheets.get('Value Labels')
    
    if value_labels_sheet is not None:
        # Find the column names
        var_col = None
        labels_col = None
        for col in value_labels_sheet.columns:
            col_lower = str(col).lower()
            if 'variable' in col_lower and 'label' not in col_lower:
                var_col = col
            elif 'label' in col_lower:
                labels_col = col
        
        if var_col and labels_col:
            current_variable = None
            
            for _, row in value_labels_sheet.iterrows():
                var_name = row[var_col]
                label_text = row[labels_col]
                
                # If Variable column has a value, it's a new variable
                if pd.notna(var_name):
                    current_variable = str(var_name).strip().lower()
                    # Initialize if not exists
                    if current_variable not in enum_mappings:
                        enum_mappings[current_variable] = {
                            "description": descriptions.get(current_variable, ""),
                            "enums": {}
                        }
                
                # Parse the Variable Labels column for enum definitions
                # Format: '0="Missing"', '1="Political Expression"', '2=\'One Day\'', '3= NULL'
                if pd.notna(label_text) and current_variable:
                    label_text = str(label_text).strip()
                    
                    # Pattern to match: key="value" or key='value' or key= NULL (case-insensitive) or key=value
                    # Match patterns like: 0="Missing", 1='One Day', 3= NULL, 4=NULL
                    # More flexible pattern to handle various formats
                    pattern = r'^(\d+|\w+)\s*=\s*(?:"([^"]*)"|\'([^\']*)\'|(NULL|null)\s*|(.+?)(?:\s*$))'
                    match = re.match(pattern, label_text, re.IGNORECASE)
                    
                    if match:
                        enum_key = match.group(1).strip()
                        # Get the value from whichever group matched (group 2=double quotes, 3=single quotes, 4=NULL, 5=unquoted)
                        enum_value = (match.group(2) or match.group(3) or 
                                     (match.group(4) if match.group(4) else "") or
                                     (match.group(5).strip() if match.group(5) else ""))
                        
                        if enum_key:
                            # Normalize NULL values
                            if enum_value.upper() == "NULL" or enum_value == "":
                                enum_value = "NULL"
                            enum_mappings[current_variable]["enums"][enum_key] = enum_value.strip()
    
    # Step 3: Also add variables that have descriptions but no enum values
    for var_name, desc in descriptions.items():
        if var_name not in enum_mappings:
            enum_mappings[var_name] = {
                "description": desc,
                "enums": {}
            }
    
    return enum_mappings

# Create the mapping
enum_mappings = create_enum_mapping(codebook_sheets)
print(f"\n\nFound {len(enum_mappings)} variables with mappings")
print(f"\nSample mappings:")
for var_name, mapping in list(enum_mappings.items())[:]:
    print(f"\n{var_name}:")
    print(f"  Description: {mapping['description'][:80]}..." if len(mapping['description']) > 80 else f"  Description: {mapping['description']}")
    print(f"  Enums: {len(mapping['enums'])} values")
    if mapping['enums']:
        sample_enums = dict(list(mapping['enums'].items())[:3])
        print(f"    Sample: {sample_enums}")

Found 105 variables with mappings

Sample mappings:

ev_type:
  Description: Event type
  Enums: 7 values
    Sample: {'0': 'Missing', '1': 'Political Expression', '2': 'Political Attacks'}

posthoc:
  Description: Post hoc reaction?
  Enums: 2 values
    Sample: {'0': 'No Post Hoc Reaction', '1': 'Destabilizing Event is a Reaction to a Prior Event'}

link_type:
  Description: Type of event link
  Enums: 2 values
    Sample: {'0': 'Part of', '1': 'Stems from'}

region:
  Description: Eight category world region variable
  Enums: 8 values
    Sample: {'1': 'SS Africa', '2': 'Asia', '3': 'Europe'}

loc_type:
  Description: Event location type
  Enums: 29 values
    Sample: {'0': 'Whole Country', '1': 'Sparsely Populated Area', '2': 'Densely Populated Area'}

date_typ:
  Description: Type of date information available
  Enums: 4 values
    Sample: {'1': 'Precise Single Day', '2': 'Precise Multi-day', '3': 'Estimated Single Day'}

pe_type:
  Description: Type of political expression event
  Enums: 11 values
    Sample: {'1': 'Verbal', '2': 'Broadcast', '3': 'Movie, Play, Etc.'}

exp_type:
  Description: Reduced political expression type
  Enums: 4 values
    Sample: {'1': 'Verbal or Written Expression', '2': 'Symbolic Act', '3': 'Forming an Association'}

sym_type:
  Description: Type of symbolic event
  Enums: 15 values
    Sample: {'1': 'Passive Resistance', '2': 'Praying', '3': 'Boycott'}

ad_viol:
  Description: Were violent acts advocated?
  Enums: 4 values
    Sample: {'0': 'No Violence Advocated', '1': 'Violence Advocated', '2': 'Not Relevant'}

ad_tact:
  Description: Tactics advocated in political exp
  Enums: 18 values
    Sample: {'1': 'Civil Disobedience', '2': 'Symbolic Actions', '3': 'Disrespect to Nat Symbols'}

atk_type:
  Description: Type of political motivated attack
  Enums: 23 values
    Sample: {'1': 'Riot or Brawl', '2': 'Assassination', '3': 'Suicide Attack'}

dsa_type:
  Description: Broad category of disruptive state act
  Enums: 5 values
    Sample: {'1': 'Minimal State Act', '2': 'Formal State Act', '3': 'Use of Coercive Force'}

stat_act:
  Description: Type of disruptive state act
  Enums: 57 values
    Sample: {'1': 'Censorship', '2': 'Disrupting Electronic Comm', '3': 'Banning Civil Society Group'}

victim_effect:
  Description: Impact of event on victim
  Enums: 13 values
    Sample: {'1': 'No Known Effects', '2': 'General Effects', '3': 'Constrained'}

weapon:
  Description: Type of weapon used
  Enums: 27 values
    Sample: {'1': 'No Weapon', '2': 'Crude Weapons', '3': 'Small Arms'}

property_damaged:
  Description: Type of property damaged
  Enums: 47 values
    Sample: {'1': 'Computer', '2': 'Motor Vehicle', '3': 'Flag'}

property_owner:
  Description: Type of owner for damaged property
  Enums: 12 values
    Sample: {'1': 'Private Individual', '2': 'Religious Group', '3': 'Political Group'}

gp_type:
  Description: Type of geo-political entity targeted
  Enums: 5 values
    Sample: {'1': 'Specific Neighborhood', '2': 'Specific City', '3': 'State/Province'}

know_ini:
  Description: Was the id of the initiator known?
  Enums: 3 values
    Sample: {'0': 'Initiator Unknown', '1': 'Initiator Known', '2': 'Ambiguous Initiator'}

ini_type:
  Description: Type of initiator
  Enums: 5 values
    Sample: {'1': 'Non Gov Initiator', '2': 'Gov Initiator', '3': 'Suspected Gov Initiator'}

tar_type:
  Description: Type of target
  Enums: 5 values
    Sample: {'0': 'No Target', '1': 'Human', '2': 'Property'}

vic_type:
  Description: Type of entity victimized
  Enums: 3 values
    Sample: {'1': 'Human', '2': 'Property', '3': 'Geo-political Entity'}

ngov_i1:
  Description: Type of non-government initiators
  Enums: 41 values
    Sample: {'1': 'Social Group Member', '2': 'Political Group Member', '3': 'Union Member'}

gov_i1:
  Description: Type of government initiator, 1
  Enums: 24 values
    Sample: {'1': 'Fire/rescue Official', '2': 'Police Officer', '3': 'Soldier'}

g_lvl_t:
  Description: Level of government target
  Enums: 4 values
    Sample: {'1': 'Local Government', '2': 'Provincial Government', '3': 'National Government'}

e_length:
  Description: Length of event, truncated
  Enums: 4 values
    Sample: {'1': 'One Day', '2': 'Two to Seven Days', '3': 'One Week to a Month'}

eventid:
  Description: Event identification number
  Enums: 0 values

country:
  Description: Country in which the event occurred
  Enums: 0 values

cowcode:
  Description: Cowcode of country where event occurred
  Enums: 0 values

ini_igrp1:
  Description: Name of insurgent group initiator
  Enums: 0 values

tar_igrp1:
  Description: Name of insurgent group target
  Enums: 0 values

vic_igrp1:
  Description: Name of insurgent group victim
  Enums: 0 values

ini_sgrp1:
  Description: Name of socio-cultural group initiator
  Enums: 0 values

tar_sgrp1:
  Description: Name of socio-cultural group target
  Enums: 0 values

vic_sgrp1:
  Description: Name of socio-cultural group victim
  Enums: 0 values

ini_pgrp1:
  Description: Name of political group initiator
  Enums: 0 values

tar_pgrp1:
  Description: Name of political group target
  Enums: 0 values

vic_pgrp1:
  Description: Name of political group victim
  Enums: 0 values

ambig_ini:
  Description: Ambiguous initiator/target distinction
  Enums: 0 values

human_t1:
  Description: Type of human target
  Enums: 0 values

gov_t1:
  Description: Type of government target
  Enums: 0 values

g_lvl_i:
  Description: Level of government initiator
  Enums: 0 values

g_lvl_v:
  Description: Level of government victim
  Enums: 0 values

human_v1:
  Description: Type of human victim
  Enums: 0 values

gov_v1:
  Description: Type of government victim
  Enums: 0 values

day:
  Description: Day of event - multi-day=average
  Enums: 0 values

month:
  Description: Month of event - multi-day=average
  Enums: 0 values

year:
  Description: Year of event - multi-day=average
  Enums: 0 values

jul_psd:
  Description: Precise julian date of event start
  Enums: 0 values

jul_ped:
  Description: Precise julian date of event end (Julian Date = 0 on Janurary 1st, 1945)
  Enums: 0 values

jul_eed:
  Description: Estimated julian date of event start (Julian Date = 0 on Janurary 1st, 1945)
  Enums: 0 values

jul_led:
  Description: Estimated julian date of event end (Julian Date = 0 on Janurary 1st, 1945)
  Enums: 0 values

jul_start_date:
  Description: Earliest start day of event (Julian Date = 0 on Janurary 1st, 1945)
  Enums: 0 values

jul_end_date:
  Description: Latest end day of event
  Enums: 0 values

day_span:
  Description: Longest span of event, in days
  Enums: 0 values

n_injurd:
  Description: # Of individuals injured
  Enums: 0 values

tar_gpol:
  Description: Was the target a geo-political entity
  Enums: 0 values

aid:
  Description: Article id#
  Enums: 0 values

pub_mon:
  Description: Global_pubdate_month
  Enums: 0 values

pub_date:
  Description: Global_pubdate_day
  Enums: 0 values

pub_year:
  Description: Global_pubdate_year
  Enums: 0 values

recap:
  Description: Is this a recapitulation coding?
  Enums: 0 values

news_source:
  Description: Source of the coded article
  Enums: 0 values

code_year:
  Description: Year of coding
  Enums: 0 values

code_month:
  Description: Month of coding
  Enums: 0 values

code_day:
  Description: Day of coding
  Enums: 0 values

event:
  Description: Is this coding for a destabilizing event?
  Enums: 0 values

linked:
  Description: Is this a linked coding?
  Enums: 0 values

from_eid:
  Description: Id of event linked from
  Enums: 0 values

to_eid:
  Description: Id of event linked to
  Enums: 0 values

pinpoint:
  Description: Type of geospatial data available
  Enums: 0 values

gp3:
  Description: Country name(caps and lower case)
  Enums: 0 values

gp4:
  Description: Lowest level entity name (caps and lower case)
  Enums: 0 values

gp7:
  Description: Latitude
  Enums: 0 values

gp8:
  Description: Longitude
  Enums: 0 values

n_of_ini_p:
  Description: Pristine measure of # of initiators
  Enums: 0 values

n_of_ini_a:
  Description: Measure of # of initiators with statistical estimates
  Enums: 0 values

weap_grd:
  Description: 5 category weapon variable
  Enums: 0 values

n_killed_p:
  Description: Pristine estimate of # killed, from news report
  Enums: 0 values

n_killed_a:
  Description: Estimate of # killed, including statistical estimates
  Enums: 0 values

n_injurd_d:
  Description: # Injured, max=10
  Enums: 0 values

dam_prop:
  Description: Was property damaged in the event?
  Enums: 0 values

arrests:
  Description: Were arrests made?
  Enums: 0 values

per_atk_i:
  Description: Integrated attack against a human variable
  Enums: 0 values

per_atk_e:
  Description: Extraordinary violent attack against a human
  Enums: 0 values

pub_order:
  Description: Event rooted in desire to maintain pub order?
  Enums: 0 values

retribution:
  Description: Event rooted in desire for retribution?
  Enums: 0 values

pol_express:
  Description: Intensity of small-bore political expression
  Enums: 0 values

intang_rep:
  Description: Level of intangible repression
  Enums: 0 values

mass_express:
  Description: Intensity of mass expression
  Enums: 0 values

pol_viol:
  Description: Intensity of political violence
  Enums: 0 values

stat_viol:
  Description: Intensity of state violence
  Enums: 0 values

st_repress:
  Description: Intensity of tang state repression
  Enums: 0 values

ambig_wgt:
  Description: Weight to adjust for double counting initiators
  Enums: 0 values

sc_animosity:
  Description: Event rooted in socio-cultural animosities?
  Enums: 0 values

anti_gov_sentmnts:
  Description: Event rooted in anti-government sentiments?
  Enums: 0 values

class_conflict:
  Description: Event rooted in class-based conflict?
  Enums: 0 values

pol_desires:
  Description: Event rooted in desire for political rights?
  Enums: 0 values

retain_power:
  Description: Event rooted in desire to retain political power?
  Enums: 0 values

eco_scarcity:
  Description: Event rooted in ecological resource scarcities
  Enums: 0 values

pers_security:
  Description: Event rooted in desire for personal security?
  Enums: 0 values

quasi_event:
  Description: Is this a quasi-event coding?
  Enums: 0 values

coup:
  Description: Did this event involve a coup?
  Enums: 0 values

coup_failed:
  Description: Did this event involve an unrealized coup?
  Enums: 0 values

## 4. Take Sample Rows and Resolve Enum Values

In [46]:
# Function to resolve enum values in a dataframe
def resolve_enums(df, enum_mappings, sample_size=5):
    """
    Take sample rows and create a new dataframe with resolved enum values.
    
    enum_mappings structure:
    {
        column_name: {
            "description": "...",
            "enums": {key: value}
        }
    }
    """
    # Take sample rows
    sample_df = df.head(sample_size).copy()
    
    # Create a resolved version
    resolved_df = sample_df.copy()
    
    # For each column in the sample, try to resolve if mapping exists
    resolved_info = {}
    
    for col in sample_df.columns:
        # Try to find matching enum mapping (case-insensitive)
        matching_var = None
        for var_name in enum_mappings.keys():
            if col.lower() == var_name.lower() or col.lower().replace('_', '') == var_name.lower().replace('_', ''):
                matching_var = var_name
                break
        
        if matching_var and enum_mappings[matching_var].get("enums"):
            # Get the enum mappings for this variable
            enum_dict = enum_mappings[matching_var]["enums"]
            
            # Create resolved column
            resolved_col_name = f"{col}_resolved"
            
            def resolve_enum_value(value):
                """Resolve enum value, handling float to int conversion"""
                if pd.isna(value):
                    return value
                
                # Convert to string and strip whitespace
                value_str = str(value).strip()
                
                # Try original value as string first (handles cases like "1.0" as string)
                if value_str in enum_dict:
                    return enum_dict[value_str]
                
                # Try converting to numeric and then to int for enum lookup
                try:
                    # First try as float
                    float_val = float(value_str)
                    
                    # If it's a whole number, try as int string
                    if float_val.is_integer():
                        int_val = int(float_val)
                        int_str = str(int_val)
                        if int_str in enum_dict:
                            return enum_dict[int_str]
                    
                    # Also try the float string representation (e.g., "22.0")
                    float_str = str(int(float_val)) if float_val.is_integer() else value_str
                    if float_str in enum_dict:
                        return enum_dict[float_str]
                        
                except (ValueError, OverflowError, TypeError):
                    pass
                
                # If value is already a float/numeric type, try direct int conversion
                try:
                    if isinstance(value, (float, int)) and not pd.isna(value):
                        int_val = int(value)
                        int_str = str(int_val)
                        if int_str in enum_dict:
                            return enum_dict[int_str]
                except (ValueError, OverflowError):
                    pass
                
                # Return original value if no match found (could be a value not in codebook)
                return value
            
            resolved_df[resolved_col_name] = sample_df[col].apply(resolve_enum_value)
            resolved_info[col] = {
                'mapping_var': matching_var,
                'description': enum_mappings[matching_var].get("description", ""),
                'unique_values': sample_df[col].unique(),
                'resolved_values': resolved_df[resolved_col_name].unique()
            }
    
    return resolved_df, resolved_info

# Get sample rows with resolved enums
sample_size = 62141
resolved_df, resolved_info = resolve_enums(df, enum_mappings, sample_size=sample_size)

print(f"Sample of {sample_size} rows with resolved enum values:\n")
display(resolved_df)

Sample of 62141 rows with resolved enum values:

,cowcode,month,year,eventid,country,INI_IGRP1,TAR_IGRP1,VIC_IGRP1,INI_SGRP1,TAR_SGRP1,VIC_SGRP1,INI_PGRP1,TAR_PGRP1,VIC_PGRP1,KNOW_INI,AMBIG_INI,INI_TYPE,NGOV_I1,GOV_I1,TAR_TYPE,HUMAN_T1,GOV_T1,G_LVL_I,G_LVL_T,G_LVL_V,HUMAN_V1,GOV_V1,VIC_TYPE,DATE_TYP,day,JUL_PSD,JUL_PED,JUL_EED,JUL_LED,JUL_START_DATE,JUL_END_DATE,DAY_SPAN,N_INJURD,TAR_GPOL,GP_TYPE,aid,PUB_MON,PUB_DATE,PUB_YEAR,recap,NEWS_SOURCE,CODE_YEAR,CODE_MONTH,CODE_DAY,event,posthoc,EV_TYPE,linked,LINK_TYPE,FROM_EID,TO_EID,pinpoint,GP3,GP4,GP7,GP8,LOC_TYPE,PE_TYPE,SYM_TYPE,AD_VIOL,AD_TACT,EXP_TYPE,ATK_TYPE,DSA_TYPE,STAT_ACT,N_OF_INI_P,N_OF_INI_A,WEAP_GRD,N_KILLED_P,N_KILLED_A,E_LENGTH,N_INJURD_D,DAM_PROP,arrests,PER_ATK_I,PER_ATK_E,PUB_ORDER,retribution,POL_EXPRESS,INTANG_REP,MASS_EXPRESS,POL_VIOL,STAT_VIOL,ST_REPRESS,AMBIG_WGT,SC_ANIMOSITY,ANTI_GOV_SENTMNTS,CLASS_CONFLICT,POL_DESIRES,RETAIN_POWER,ECO_SCARCITY,PERS_SECURITY,QUASI_EVENT,coup,COUP_FAILED,region,ctry_bias,victim_effect,weapon,property_damaged,property_owner,KNOW_INI_resolved,INI_TYPE_resolved,NGOV_I1_resolved,GOV_I1_resolved,TAR_TYPE_resolved,G_LVL_T_resolved,VIC_TYPE_resolved,DATE_TYP_resolved,GP_TYPE_resolved,posthoc_resolved,EV_TYPE_resolved,LINK_TYPE_resolved,LOC_TYPE_resolved,PE_TYPE_resolved,SYM_TYPE_resolved,AD_VIOL_resolved,AD_TACT_resolved,EXP_TYPE_resolved,ATK_TYPE_resolved,DSA_TYPE_resolved,STAT_ACT_resolved,E_LENGTH_resolved,region_resolved,victim_effect_resolved,weapon_resolved,property_damaged_resolved,property_owner_resolved
0,NaN,NaN,1946,EID40124,NaN,.,.,.,.,.,.,.,.,.,1.0,0,1.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,593.0,593.0,593.0,593.0,NaN,NaN,NaN,0,0,NaN,19194629.0,8,17,1946,0,NYT,2009,4,18,1,0,1.0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,4.0,NaN,0,17.0,1.0,NaN,NaN,NaN,1.0,1.0,1.0,0.0,0,1,0,0,0,0,0,0,0,1.0,NaN,NaN,NaN,NaN,NaN,0.0,0,0,1,0,0,0,0,0,0,0,NaN,NaN,1.0,1,NaN,NaN,Initiator Known,Non Gov Initiator,Local Leader,NaN,NaN,NaN,Human,NaN,NaN,No Post Hoc Reaction,Political Expression,NaN,Unspecified Location,Written,NaN,No Violence Advocated,None,Verbal or Written Expression,NaN,NaN,NaN,One Day,NaN,No Known Effects,No Weapon,NaN,NaN
1,NaN,NaN,1946,EID51193,NaN,.,.,.,.,.,.,.,.,.,1.0,0,2.0,NaN,3.0,3.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,398.0,398.0,NaN,NaN,NaN,NaN,NaN,0,1,5.0,2159468.0,2,3,1946,0,NYT,2009,6,24,1,0,1.0,1,0.0,EID51193,EID51194,2.0,NaN,NaN,NaN,NaN,22.0,8.0,NaN,0,17.0,4.0,NaN,NaN,NaN,NaN,30.0,1.0,0.0,0,1,0,0,0,0,0,0,0,NaN,NaN,1.0,NaN,NaN,NaN,0.0,0,0,1,0,0,0,0,0,0,0,NaN,NaN,NaN,1,NaN,NaN,Initiator Known,Gov Initiator,NaN,Soldier,Geo Pol Entity,NaN,NaN,NaN,Entire Nation,No Post Hoc Reaction,Political Expression,Part of,Military Facility,Job Action,NaN,No Violence Advocated,None,Mass Demonstration or Strike,NaN,NaN,NaN,One Day,NaN,NaN,No Weapon,NaN,NaN
2,NaN,11.0,1948,EID133296,NaN,.,.,.,.,.,.,Association Of Catholic Trade Unionists,.,.,1.0,0,1.0,6.0,NaN,1.0,37.0,10.0,NaN,3.0,3.0,37.0,10.0,NaN,1.0,15.0,1415.0,1415.0,NaN,NaN,1415.0,1415.0,1.0,0,0,NaN,19354824.0,11,16,1948,0,NYT,2010,4,11,1,0,1.0,0,NaN,NaN,NaN,3.0,FALKLAND ISLANDS (ISLAS MALVINAS),FALKLAND ISLANDS (ISLAS MALVINAS),-51.750000,-59.000000,2.0,7.0,NaN,0,17.0,4.0,NaN,NaN,NaN,NaN,1250.0,1.0,0.0,0,1,0,0,0,0,0,0,0,NaN,NaN,1.1,NaN,NaN,NaN,0.0,1,1,1,0,0,0,0,0,0,0,NaN,NaN,13.0,1,NaN,NaN,Initiator Known,Non Gov Initiator,Worker,NaN,Human,National Government,NaN,Precise Single Day,NaN,No Post Hoc Reaction,Political Expression,NaN,Densely Populated Area,Demonstration/March,NaN,No Violence Advocated,None,Mass Demonstration or Strike,NaN,NaN,NaN,One Day,NaN,Some Other Effect,No Weapon,NaN,NaN
3,NaN,9.0,1951,EID102797,NaN,.,.,.,.,.,.,.,.,.,1.0,0,1.0,5.0,NaN,1.0,37.0,18.0,NaN,3.0,3.0,37.0,18.0,NaN,1.0,8.0,2442.0,2442.0,NaN,NaN,2442.0,2442.0,1.0,0,0,NaN,19669349.0,9,9,1951,0,NYT,2010,1,29,1,0,1.0,0,NaN,NaN,NaN,3.0,JERSEY,JERSEY,49.216702,-2.116670,2.0,9.0,15.0,0,17.0,2.0,NaN,NaN,NaN,NaN,7.0,2.0,0.0,0,1,0,0,0,0,0,0,0,1.9,NaN,NaN,NaN,NaN,NaN,0.0,0,1,0,0,0,0,0,0,0,0,NaN,NaN,13.0,13,NaN,NaN,Initiator Known,Non Gov Initiator,Nondescript Individual,NaN,Human,National Government,NaN,Precise Single Day,NaN,No Post Hoc Reaction,Political Expression,NaN,Densely Populated Area,Symbolic Act,Other,No Violence Advocated,None,Symbolic Act,NaN,NaN,NaN,One Day,NaN,Some Other Effect,Non-lethal Projectiles,NaN,NaN
4,NaN,7.0,1952,EID257135,NaN,.,.,.,.,.,.,.,.,.,2.0,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,30.0,2768.0,2768.0,NaN,NaN,2768.0,2768.0,1.0,0,0,NaN,19881693.0,7,31,1952,0,NYT,2011,6,1,1,0,2.0,0,NaN,NaN,NaN,3.0,MACAU,MACAO,22.200600,113.545998,2.0,NaN,NaN,0,NaN,NaN,6.0,NaN,NaN,NaN,NaN,1.0,0.0,0,1,0,0,0,1,0,0,0,NaN,NaN,NaN,2.8,NaN,NaN,0.5,0,0,0,0,0,0,0,0,0,0,NaN,NaN,13.0,1,NaN,NaN,Ambiguous Initiator,NaN,NaN,NaN,NaN,NaN,NaN,Precise Single Day,NaN,No Post Hoc Reaction,Political Attacks,NaN,Densely Populated Area,NaN,NaN,No Violence Advocated,NaN,NaN,Other Personal Attack,NaN,NaN,One Day,NaN,Some Other Effect,No Weapon,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62136,950.0,11.0,2000,EID173326,Fiji,.,.,.,.,.,.,.,.,.,0.5,0,2.0,18.0,NaN,1.0,37.0,17.0,NaN,NaN,NaN,37.0,17.0,NaN,3.0,20.0,NaN,NaN,20409.0,20414.0,20409.0,20414.0,6.0,0,0,NaN,51771963.0,11,22,2000,0,SWB,2010,7,20,1,0,1.0,0,NaN,NaN,NaN,3.0,FIJI,FIJI,-18.000000,175.000000,2.0,7.0,NaN,0,17.0,4.0,NaN,NaN,NaN,NaN,1250.0,1.0,0.0,0,1,0,0,0,0,0,0,0,NaN,NaN,1.1,NaN,NaN,NaN,0.0,0,0,0,0,0,0,0,0,0,0,6.0,1.1,13.0,1,NaN,NaN,Initiator Unknown,Gov Initiator,Dissident,NaN,Human,NaN,NaN,Estimated Single Day,NaN,No Post Hoc Reaction,Political Expression,NaN,Densely Populated Area,Demonstration/March,NaN,No Violence Advocated,None,Mass Demonstration or Strike,NaN,NaN,NaN,One Day,Oceania,Some Other Effect,No Weapon,NaN,NaN
62137,950.0,11.0,2000,EID174122,Fiji,.,.,.,.,.,.,.,.,.,1.0,0,2.0,NaN,20.0,4.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,1.0,25.0,20417.0,20417.0,NaN,NaN,20417.0,20417.0,1.0,0,0,NaN,51775531.0,11,26,2000,0,SWB,2010,7,21,1,0,4.0,0,NaN,NaN,NaN,1.0,FIJI,FIJI,-18.000000,175.000000,27.0,NaN,NaN,0,NaN,NaN,NaN,1.0,19.0,NaN,NaN,1.0,0.0,0,1,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0,0,0,0,0,0,0,0,0,0,6.0,1.1,NaN,1,NaN,NaN,Initiator Known,Gov Initiator,NaN,Government (Corporate),Unspecified Target,NaN,NaN,Precise Single Day,NaN,No Post Hoc Reaction,Disruptive State Acts,NaN,Unspecified Location,NaN,NaN,No Violence Advocated,NaN,NaN,NaN,Minimal State Act,Assembly of Coercive Forces,One Day,Oceania,NaN,No Weapon,NaN,NaN
62138,983.0,3.0,1954,EID43038,Marshall Islands,.,.,.,.,.,.,.,.,.,1.0,0,2.0,NaN,3.0,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,3347.0,3347.0,3361.0,3361.0,3347.0,3347.0,1.0,0,0,NaN,20064479.0,3,16,1954,0,NYT,2009,5,2,1,0,NaN,1,0.0,EID43038,EID43039,NaN,MARSHALL ISLANDS,BIKINI,11.616700,165.550003,25.0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,0.0,0,1,0,0,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,0,0,0,0,0,0,0,0,0,NaN,1.0,NaN,25,NaN,NaN,Initiator Known,Gov Initiator,NaN,Soldier,NaN,NaN,NaN,Precise Single Day,NaN,No Post Hoc Reaction,NaN,Part of,Water Space,NaN,NaN,No Violence Advocated,NaN,NaN,NaN,NaN,NaN,One Day,NaN,NaN,Biochemical Weapons,NaN,NaN
62139,983.0,3.0,1954,EID43039,Marshall Islands,.,.,.,.,.,.,.,.,.,1.0,0,2.0,NaN,3.0,3.0,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,3347.0,3347.0,3361.0,3361.0,3347.0,3347.0,1.0,0,1,5.0,20064479.0,3,16,1954,0,NYT,2009,5,2,1,0,1.0,0,NaN,NaN,NaN,NaN,MARSHALL ISLANDS,BIKINI,11.616700,165.550003,27.0,1.0,NaN,0,17.0,1.0,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0,1,0,0,0,0,0,0,0,1.0,NaN,NaN,NaN,NaN,NaN,0.0,0,0,0,0,0,0,0,0,0,0,NaN,1.0,NaN,1,NaN,NaN,Initiator Known,Gov Initiator,NaN,Soldier,Geo Pol Entity,NaN,NaN,Precise Single Day,Entire Nation,No Post Hoc Reaction,Political Expression,NaN,Unspecified Location,Verbal,NaN,No Violence Advocated,None,Verbal or Written Expression,NaN,NaN,NaN,One Day,NaN,NaN,No Weapon,NaN,NaN
62140,990.0,12.0,1973,EID51410,American Samoa,.,.,.,.,.,.,.,.,.,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,1.0,10563.0,10563.0,10563.0,10563.0,10563.0,10563.0,1.0,0,0,NaN,21835327.0,12,2,1973,0,NYT,2009,6,27,1,0,NaN,0,NaN,NaN,NaN,3.0,AMERICAN SAMOA,AMERICAN SAMOA,-15.072100,-170.485992,21.0,NaN,NaN,0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0,1,0,1,0,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0,0,0,0,0,0,0,0,0,0,NaN,1.0,NaN,1,43.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Property,Precise Single Day,NaN,No Post Hoc Reaction,NaN,NaN,Government Facility,NaN,NaN,No Violence Advocated,None,NaN,NaN,NaN,NaN,One Day,NaN,NaN,No Weapon,Government Facility,NaN

## 4.1. Diagnostic: Check Resolution Status

In [47]:
# Diagnostic: Check which values were resolved and which weren't
print("Resolution Diagnostic:\n")
print("=" * 80)

for col in resolved_info.keys():
    print(f"\nColumn: {col}")
    print(f"  Mapping Variable: {resolved_info[col]['mapping_var']}")
    
    # Check original vs resolved values
    original_vals = resolved_df[col].dropna().unique()
    resolved_vals = resolved_df[f"{col}_resolved"].dropna().unique()
    
    # Find values that weren't resolved (original value == resolved value and it's numeric)
    unresolved = []
    for idx in resolved_df.index:
        orig = resolved_df.loc[idx, col]
        resolved = resolved_df.loc[idx, f"{col}_resolved"]
        if pd.notna(orig) and pd.notna(resolved):
            # If resolved value is the same as original (numeric), it wasn't resolved
            try:
                if float(orig) == float(resolved):
                    unresolved.append(orig)
            except (ValueError, TypeError):
                if str(orig) == str(resolved):
                    unresolved.append(orig)
    
    if unresolved:
        print(f"  ⚠ Unresolved values: {set(unresolved)}")
        # Check if these values exist in enum_dict
        enum_dict = enum_mappings[resolved_info[col]['mapping_var']].get("enums", {})
        for val in set(unresolved):
            val_str = str(int(val)) if isinstance(val, float) and val.is_integer() else str(val)
            if val_str not in enum_dict:
                print(f"    - {val} ({val_str}) not found in enum mappings")
            else:
                print(f"    - {val} ({val_str}) exists in mappings but wasn't resolved")
    else:
        print(f"  ✓ All non-null values resolved")
    
    print(f"  Original unique values: {len(original_vals)}")
    print(f"  Resolved unique values: {len(resolved_vals)}")
    print("-" * 80)

Resolution Diagnostic:

================================================================================

Column: KNOW_INI
  Mapping Variable: know_ini
  ✓ All non-null values resolved
  Original unique values: 4
  Resolved unique values: 3
--------------------------------------------------------------------------------

Column: INI_TYPE
  Mapping Variable: ini_type
  ✓ All non-null values resolved
  Original unique values: 5
  Resolved unique values: 5
--------------------------------------------------------------------------------

Column: NGOV_I1
  Mapping Variable: ngov_i1
  ✓ All non-null values resolved
  Original unique values: 41
  Resolved unique values: 41
--------------------------------------------------------------------------------

Column: GOV_I1
  Mapping Variable: gov_i1
  ✓ All non-null values resolved
  Original unique values: 24
  Resolved unique values: 24
--------------------------------------------------------------------------------

Column: TAR_TYPE
  Mapping Variable: tar_type
  ✓ All non-null values resolved
  Original unique values: 5
  Resolved unique values: 5
--------------------------------------------------------------------------------

Column: G_LVL_T
  Mapping Variable: g_lvl_t
  ✓ All non-null values resolved
  Original unique values: 4
  Resolved unique values: 4
--------------------------------------------------------------------------------

Column: VIC_TYPE
  Mapping Variable: vic_type
  ✓ All non-null values resolved
  Original unique values: 3
  Resolved unique values: 3
--------------------------------------------------------------------------------

Column: DATE_TYP
  Mapping Variable: date_typ
  ✓ All non-null values resolved
  Original unique values: 4
  Resolved unique values: 4
--------------------------------------------------------------------------------

Column: GP_TYPE
  Mapping Variable: gp_type
  ✓ All non-null values resolved
  Original unique values: 5
  Resolved unique values: 5
--------------------------------------------------------------------------------

Column: posthoc
  Mapping Variable: posthoc
  ✓ All non-null values resolved
  Original unique values: 2
  Resolved unique values: 2
--------------------------------------------------------------------------------

Column: EV_TYPE
  Mapping Variable: ev_type
  ✓ All non-null values resolved
  Original unique values: 4
  Resolved unique values: 4
--------------------------------------------------------------------------------

Column: LINK_TYPE
  Mapping Variable: link_type
  ✓ All non-null values resolved
  Original unique values: 2
  Resolved unique values: 2
--------------------------------------------------------------------------------

Column: LOC_TYPE
  Mapping Variable: loc_type
  ✓ All non-null values resolved
  Original unique values: 29
  Resolved unique values: 29
--------------------------------------------------------------------------------

Column: PE_TYPE
  Mapping Variable: pe_type
  ✓ All non-null values resolved
  Original unique values: 11
  Resolved unique values: 11
--------------------------------------------------------------------------------

Column: SYM_TYPE
  Mapping Variable: sym_type
  ✓ All non-null values resolved
  Original unique values: 15
  Resolved unique values: 15
--------------------------------------------------------------------------------

Column: AD_VIOL
  Mapping Variable: ad_viol
  ✓ All non-null values resolved
  Original unique values: 2
  Resolved unique values: 2
--------------------------------------------------------------------------------

Column: AD_TACT
  Mapping Variable: ad_tact
  ✓ All non-null values resolved
  Original unique values: 18
  Resolved unique values: 18
--------------------------------------------------------------------------------

Column: EXP_TYPE
  Mapping Variable: exp_type
  ✓ All non-null values resolved
  Original unique values: 4
  Resolved unique values: 4
--------------------------------------------------------------------------------

Column: ATK_TYPE
  Mapping Variable: atk_type
  ✓ All non-null values resolved
  Original unique values: 10
  Resolved unique values: 10
--------------------------------------------------------------------------------

Column: DSA_TYPE
  Mapping Variable: dsa_type
  ✓ All non-null values resolved
  Original unique values: 5
  Resolved unique values: 5
--------------------------------------------------------------------------------

Column: STAT_ACT
  Mapping Variable: stat_act
  ✓ All non-null values resolved
  Original unique values: 42
  Resolved unique values: 42
--------------------------------------------------------------------------------

Column: E_LENGTH
  Mapping Variable: e_length
  ✓ All non-null values resolved
  Original unique values: 4
  Resolved unique values: 4
--------------------------------------------------------------------------------

Column: region
  Mapping Variable: region
  ✓ All non-null values resolved
  Original unique values: 8
  Resolved unique values: 8
--------------------------------------------------------------------------------

Column: victim_effect
  Mapping Variable: victim_effect
  ✓ All non-null values resolved
  Original unique values: 13
  Resolved unique values: 13
--------------------------------------------------------------------------------

Column: weapon
  Mapping Variable: weapon
  ✓ All non-null values resolved
  Original unique values: 27
  Resolved unique values: 26
--------------------------------------------------------------------------------

Column: property_damaged
  Mapping Variable: property_damaged
  ✓ All non-null values resolved
  Original unique values: 42
  Resolved unique values: 42
--------------------------------------------------------------------------------

Column: property_owner
  Mapping Variable: property_owner
  ✓ All non-null values resolved
  Original unique values: 12
  Resolved unique values: 12
--------------------------------------------------------------------------------

## 5. Display Enum Resolution Details

In [38]:
# Show detailed enum resolution for each column that was resolved
print("Enum Resolution Details:\n")
print("=" * 80)

for col, info in resolved_info.items():
    print(f"\nColumn: {col}")
    print(f"  Mapping Variable: {info['mapping_var']}")
    if info.get('description'):
        print(f"  Description: {info['description']}")
    print(f"  Original Values in Sample: {info['unique_values']}")
    print(f"  Resolved Values: {info['resolved_values']}")
    
    # Show full mapping for this variable
    if info['mapping_var'] in enum_mappings:
        enum_dict = enum_mappings[info['mapping_var']].get("enums", {})
        if enum_dict:
            print(f"\n  Full Enum Mapping for '{info['mapping_var']}':")
            for key, value in sorted(enum_dict.items(), key=lambda x: (str(x[0]).isdigit(), str(x[0])))[:10]:  # Show first 10
                print(f"    {key} -> {value}")
            if len(enum_dict) > 10:
                print(f"    ... and {len(enum_dict) - 10} more")
    print("-" * 80)

Enum Resolution Details:

================================================================================

Column: KNOW_INI
  Mapping Variable: know_ini
  Description: Was the id of the initiator known?
  Original Values in Sample: [1. 2.]
  Resolved Values: ['Initiator Known' 'Ambiguous Initiator']

  Full Enum Mapping for 'know_ini':
    0 -> Initiator Unknown
    1 -> Initiator Known
    2 -> Ambiguous Initiator
--------------------------------------------------------------------------------

Column: INI_TYPE
  Mapping Variable: ini_type
  Description: Type of initiator
  Original Values in Sample: [ 1.  2. nan]
  Resolved Values: ['Non Gov Initiator' 'Gov Initiator' nan]

  Full Enum Mapping for 'ini_type':
    1 -> Non Gov Initiator
    2 -> Gov Initiator
    3 -> Suspected Gov Initiator
    4 -> Quasi Gov Initiator
    5 -> Non-human Stimulus
--------------------------------------------------------------------------------

Column: NGOV_I1
  Mapping Variable: ngov_i1
  Description: Type of non-government initiators
  Original Values in Sample: [22. nan  6.  5.]
  Resolved Values: ['Local Leader' nan 'Worker' 'Nondescript Individual']

  Full Enum Mapping for 'ngov_i1':
    1 -> Social Group Member
    10 -> Youth
    11 -> Elderly
    12 -> Disabled
    13 -> GLBT
    14 -> Refugee
    15 -> Student
    16 -> Educator
    17 -> Intellectual
    18 -> Dissident
    ... and 31 more
--------------------------------------------------------------------------------

Column: GOV_I1
  Mapping Variable: gov_i1
  Description: Type of government initiator, 1
  Original Values in Sample: [nan  3.]
  Resolved Values: [nan 'Soldier']

  Full Enum Mapping for 'gov_i1':
    1 -> Fire/rescue Official
    10 -> Chief Executive
    11 -> Royalty
    12 -> Clerical Leader
    13 -> Dictator
    14 -> Junta Member
    15 -> Colonial Governor
    16 -> Judge
    17 -> Judicial Court
    18 -> Legislator
    ... and 14 more
--------------------------------------------------------------------------------

Column: TAR_TYPE
  Mapping Variable: tar_type
  Description: Type of target
  Original Values in Sample: [nan  3.  1.]
  Resolved Values: [nan 'Geo Pol Entity' 'Human']

  Full Enum Mapping for 'tar_type':
    0 -> No Target
    1 -> Human
    2 -> Property
    3 -> Geo Pol Entity
    4 -> Unspecified Target
--------------------------------------------------------------------------------

Column: G_LVL_T
  Mapping Variable: g_lvl_t
  Description: Level of government target
  Original Values in Sample: [nan  3.]
  Resolved Values: [nan 'National Government']

  Full Enum Mapping for 'g_lvl_t':
    1 -> Local Government
    2 -> Provincial Government
    3 -> National Government
    4 -> International Government
--------------------------------------------------------------------------------

Column: VIC_TYPE
  Mapping Variable: vic_type
  Description: Type of entity victimized
  Original Values in Sample: [ 1. nan]
  Resolved Values: ['Human' nan]

  Full Enum Mapping for 'vic_type':
    1 -> Human
    2 -> Property
    3 -> Geo-political Entity
--------------------------------------------------------------------------------

Column: DATE_TYP
  Mapping Variable: date_typ
  Description: Type of date information available
  Original Values in Sample: [nan  1.]
  Resolved Values: [nan 'Precise Single Day']

  Full Enum Mapping for 'date_typ':
    1 -> Precise Single Day
    2 -> Precise Multi-day
    3 -> Estimated Single Day
    4 -> Estimated Multi-day
--------------------------------------------------------------------------------

Column: GP_TYPE
  Mapping Variable: gp_type
  Description: Type of geo-political entity targeted
  Original Values in Sample: [nan  5.]
  Resolved Values: [nan 'Entire Nation']

  Full Enum Mapping for 'gp_type':
    1 -> Specific Neighborhood
    2 -> Specific City
    3 -> State/Province
    4 -> Region of a Country
    5 -> Entire Nation
--------------------------------------------------------------------------------

Column: posthoc
  Mapping Variable: posthoc
  Description: Post hoc reaction?
  Original Values in Sample: [0]
  Resolved Values: ['No Post Hoc Reaction']

  Full Enum Mapping for 'posthoc':
    0 -> No Post Hoc Reaction
    1 -> Destabilizing Event is a Reaction to a Prior Event
--------------------------------------------------------------------------------

Column: EV_TYPE
  Mapping Variable: ev_type
  Description: Event type
  Original Values in Sample: [1. 2.]
  Resolved Values: ['Political Expression' 'Political Attacks']

  Full Enum Mapping for 'ev_type':
    0 -> Missing
    1 -> Political Expression
    2 -> Political Attacks
    3 -> NULL
    4 -> Disruptive State Acts
    5 -> Political Reconfigurations
    9 -> Other
--------------------------------------------------------------------------------

Column: LINK_TYPE
  Mapping Variable: link_type
  Description: Type of event link
  Original Values in Sample: [nan  0.]
  Resolved Values: [nan 'Part of']

  Full Enum Mapping for 'link_type':
    0 -> Part of
    1 -> Stems from
--------------------------------------------------------------------------------

Column: LOC_TYPE
  Mapping Variable: loc_type
  Description: Event location type
  Original Values in Sample: [27. 22.  2.]
  Resolved Values: ['Unspecified Location' 'Military Facility' 'Densely Populated Area']

  Full Enum Mapping for 'loc_type':
    0 -> Whole Country
    1 -> Sparsely Populated Area
    10 -> Shopping Area
    11 -> Hotel
    12 -> Ground Transportation Center
    13 -> Airport
    14 -> Industrial Property
    15 -> Office Complex
    16 -> Religious Site
    17 -> Medical Facility
    ... and 19 more
--------------------------------------------------------------------------------

Column: PE_TYPE
  Mapping Variable: pe_type
  Description: Type of political expression event
  Original Values in Sample: [ 4.  8.  7.  9. nan]
  Resolved Values: ['Written' 'Job Action' 'Demonstration/March' 'Symbolic Act' nan]

  Full Enum Mapping for 'pe_type':
    1 -> Verbal
    10 -> Form Assoc
    11 -> Other
    2 -> Broadcast
    3 -> Movie, Play, Etc.
    4 -> Written
    5 -> Banner
    6 -> Digital
    7 -> Demonstration/March
    8 -> Job Action
    ... and 1 more
--------------------------------------------------------------------------------

Column: SYM_TYPE
  Mapping Variable: sym_type
  Description: Type of symbolic event
  Original Values in Sample: [nan 15.]
  Resolved Values: [nan 'Other']

  Full Enum Mapping for 'sym_type':
    1 -> Passive Resistance
    10 -> Resignation in Protest
    11 -> Defect
    12 -> Symbolic Throwing
    13 -> Symbolic Wearing
    14 -> Walkout
    15 -> Other
    2 -> Praying
    3 -> Boycott
    4 -> Block Egress/Regress
    ... and 5 more
--------------------------------------------------------------------------------

Column: AD_VIOL
  Mapping Variable: ad_viol
  Description: Were violent acts advocated?
  Original Values in Sample: [0]
  Resolved Values: ['No Violence Advocated']

  Full Enum Mapping for 'ad_viol':
    0 -> No Violence Advocated
    1 -> Violence Advocated
    2 -> Not Relevant
    3 -> Other
--------------------------------------------------------------------------------

Column: AD_TACT
  Mapping Variable: ad_tact
  Description: Tactics advocated in political exp
  Original Values in Sample: [17. nan]
  Resolved Values: ['None' nan]

  Full Enum Mapping for 'ad_tact':
    1 -> Civil Disobedience
    10 -> Vocal Info Campaign
    11 -> Written Info Campaign
    12 -> Trespass
    13 -> Property Damage
    14 -> Riot
    15 -> Violence
    16 -> Revolt
    17 -> None
    18 -> Other
    ... and 8 more
--------------------------------------------------------------------------------

Column: EXP_TYPE
  Mapping Variable: exp_type
  Description: Reduced political expression type
  Original Values in Sample: [ 1.  4.  2. nan]
  Resolved Values: ['Verbal or Written Expression' 'Mass Demonstration or Strike'
 'Symbolic Act' nan]

  Full Enum Mapping for 'exp_type':
    1 -> Verbal or Written Expression
    2 -> Symbolic Act
    3 -> Forming an Association
    4 -> Mass Demonstration or Strike
--------------------------------------------------------------------------------

Column: ATK_TYPE
  Mapping Variable: atk_type
  Description: Type of political motivated attack
  Original Values in Sample: [nan  6.]
  Resolved Values: [nan 'Other Personal Attack']

  Full Enum Mapping for 'atk_type':
    1 -> Riot or Brawl
    10 -> Other Type of Attack
    12 -> Attempt Assassination
    13 -> Attempt Suicide Attack
    14 -> Attempt Kidnap/Hostage
    15 -> Attempt Oth Personal Attack
    16 -> Attempt Oth Property Attack
    17 -> Conspiracy Assassination
    18 -> Conspiracy Suicide Attack
    19 -> Conspiracy Kidnap/Hostage
    ... and 13 more
--------------------------------------------------------------------------------

Column: DSA_TYPE
  Mapping Variable: dsa_type
  Description: Broad category of disruptive state act
  Original Values in Sample: [nan]
  Resolved Values: [nan]

  Full Enum Mapping for 'dsa_type':
    1 -> Minimal State Act
    2 -> Formal State Act
    3 -> Use of Coercive Force
    4 -> State Attack
    5 -> Extraordinary State Act
--------------------------------------------------------------------------------

Column: STAT_ACT
  Mapping Variable: stat_act
  Description: Type of disruptive state act
  Original Values in Sample: [nan]
  Resolved Values: [nan]

  Full Enum Mapping for 'stat_act':
    1 -> Censorship
    10 -> Cancel/Annul Elections
    11 -> Suspend Constitution
    12 -> Other Extraordinary State Act
    13 -> Failure to Act
    14 -> Warning of Formal Action
    15 -> Threat to Use Violence
    16 -> Punitive Discharge of Pub Offcl
    17 -> Job Action by Public Employees
    18 -> Mutiny by Armed Forces
    ... and 47 more
--------------------------------------------------------------------------------

Column: E_LENGTH
  Mapping Variable: e_length
  Description: Length of event, truncated
  Original Values in Sample: [1]
  Resolved Values: ['One Day']

  Full Enum Mapping for 'e_length':
    1 -> One Day
    2 -> Two to Seven Days
    3 -> One Week to a Month
    4 -> Greater than a Month
--------------------------------------------------------------------------------

Column: region
  Mapping Variable: region
  Description: Eight category world region variable
  Original Values in Sample: [nan]
  Resolved Values: [nan]

  Full Enum Mapping for 'region':
    1 -> SS Africa
    2 -> Asia
    3 -> Europe
    4 -> Latin America & Caribbean
    5 -> North America
    6 -> Oceania
    7 -> Northern Africa
    8 -> Middle East
--------------------------------------------------------------------------------

Column: victim_effect
  Mapping Variable: victim_effect
  Description: Impact of event on victim
  Original Values in Sample: [ 1. nan 13.]
  Resolved Values: ['No Known Effects' nan 'Some Other Effect']

  Full Enum Mapping for 'victim_effect':
    1 -> No Known Effects
    10 -> Injured
    11 -> Raped
    12 -> Killed
    13 -> Some Other Effect
    2 -> General Effects
    3 -> Constrained
    4 -> Arrested
    5 -> Dispersed
    6 -> Surrendered/Captured
    ... and 3 more
--------------------------------------------------------------------------------

Column: weapon
  Mapping Variable: weapon
  Description: Type of weapon used
  Original Values in Sample: [ 1 13]
  Resolved Values: ['No Weapon' 'Non-lethal Projectiles']

  Full Enum Mapping for 'weapon':
    1 -> No Weapon
    10 -> IED
    11 -> Letter Bomb
    12 -> Fire
    13 -> Non-lethal Projectiles
    14 -> Small Arms
    15 -> Light Weapon
    16 -> Incendiary Device
    17 -> Land Mine
    18 -> Explosives, Grenade
    ... and 17 more
--------------------------------------------------------------------------------

Column: property_damaged
  Mapping Variable: property_damaged
  Description: Type of property damaged
  Original Values in Sample: [nan]
  Resolved Values: [nan]

  Full Enum Mapping for 'property_damaged':
    1 -> Computer
    10 -> Encampment
    11 -> Neighborhood
    12 -> City
    13 -> Road
    14 -> Checkpoint
    15 -> Railway or Bus Station
    16 -> Bridge
    17 -> Airport
    18 -> Harbor
    ... and 37 more
--------------------------------------------------------------------------------

Column: property_owner
  Mapping Variable: property_owner
  Description: Type of owner for damaged property
  Original Values in Sample: [nan]
  Resolved Values: [nan]

  Full Enum Mapping for 'property_owner':
    1 -> Private Individual
    10 -> Government
    11 -> Unspecified Owner
    12 -> Other Type of Owner
    2 -> Religious Group
    3 -> Political Group
    4 -> Social Group
    5 -> Labor Group
    6 -> Business or Corp
    7 -> Media Organization
    ... and 2 more
--------------------------------------------------------------------------------

## 6. Summary Statistics

In [48]:
# Summary statistics
print("Dataset Summary:")
print(f"Total rows: {len(df):,}")
print(f"Total columns: {len(df.columns)}")
print(f"\nColumns with enum mappings found: {len(resolved_info)}")
print(f"Total enum mappings in codebook: {sum(len(m.get('enums', {})) for m in enum_mappings.values())}")

# Show which columns have enum mappings available
print("\nColumns that can be resolved with codebook:")
for col in df.columns:
    matching_var = None
    for var_name in enum_mappings.keys():
        if col.lower() == var_name.lower() or col.lower().replace('_', '') == var_name.lower().replace('_', ''):
            matching_var = var_name
            break
    if matching_var:
        enum_count = len(enum_mappings[matching_var].get('enums', {}))
        desc = enum_mappings[matching_var].get('description', 'No description')
        print(f"  ✓ {col} -> {matching_var} ({enum_count} enum values)")
        if desc:
            print(f"    Description: {desc[:60]}..." if len(desc) > 60 else f"    Description: {desc}")

Dataset Summary:
Total rows: 62,141
Total columns: 106

Columns with enum mappings found: 27
Total enum mappings in codebook: 382

Columns that can be resolved with codebook:
  ✓ cowcode -> cowcode (0 enum values)
    Description: Cowcode of country where event occurred
  ✓ month -> month (0 enum values)
    Description: Month of event - multi-day=average
  ✓ year -> year (0 enum values)
    Description: Year of event - multi-day=average
  ✓ eventid -> eventid (0 enum values)
    Description: Event identification number
  ✓ country -> country (0 enum values)
    Description: Country in which the event occurred
  ✓ INI_IGRP1 -> ini_igrp1 (0 enum values)
    Description: Name of insurgent group initiator
  ✓ TAR_IGRP1 -> tar_igrp1 (0 enum values)
    Description: Name of insurgent group target
  ✓ VIC_IGRP1 -> vic_igrp1 (0 enum values)
    Description: Name of insurgent group victim
  ✓ INI_SGRP1 -> ini_sgrp1 (0 enum values)
    Description: Name of socio-cultural group initiator
  ✓ TAR_SGRP1 -> tar_sgrp1 (0 enum values)
    Description: Name of socio-cultural group target
  ✓ VIC_SGRP1 -> vic_sgrp1 (0 enum values)
    Description: Name of socio-cultural group victim
  ✓ INI_PGRP1 -> ini_pgrp1 (0 enum values)
    Description: Name of political group initiator
  ✓ TAR_PGRP1 -> tar_pgrp1 (0 enum values)
    Description: Name of political group target
  ✓ VIC_PGRP1 -> vic_pgrp1 (0 enum values)
    Description: Name of political group victim
  ✓ KNOW_INI -> know_ini (3 enum values)
    Description: Was the id of the initiator known?
  ✓ AMBIG_INI -> ambig_ini (0 enum values)
    Description: Ambiguous initiator/target distinction
  ✓ INI_TYPE -> ini_type (5 enum values)
    Description: Type of initiator
  ✓ NGOV_I1 -> ngov_i1 (41 enum values)
    Description: Type of non-government initiators
  ✓ GOV_I1 -> gov_i1 (24 enum values)
    Description: Type of government initiator, 1
  ✓ TAR_TYPE -> tar_type (5 enum values)
    Description: Type of target
  ✓ HUMAN_T1 -> human_t1 (0 enum values)
    Description: Type of human target
  ✓ GOV_T1 -> gov_t1 (0 enum values)
    Description: Type of government target
  ✓ G_LVL_I -> g_lvl_i (0 enum values)
    Description: Level of government initiator
  ✓ G_LVL_T -> g_lvl_t (4 enum values)
    Description: Level of government target
  ✓ G_LVL_V -> g_lvl_v (0 enum values)
    Description: Level of government victim
  ✓ HUMAN_V1 -> human_v1 (0 enum values)
    Description: Type of human victim
  ✓ GOV_V1 -> gov_v1 (0 enum values)
    Description: Type of government victim
  ✓ VIC_TYPE -> vic_type (3 enum values)
    Description: Type of entity victimized
  ✓ DATE_TYP -> date_typ (4 enum values)
    Description: Type of date information available
  ✓ day -> day (0 enum values)
    Description: Day of event - multi-day=average
  ✓ JUL_PSD -> jul_psd (0 enum values)
    Description: Precise julian date of event start
  ✓ JUL_PED -> jul_ped (0 enum values)
    Description: Precise julian date of event end (Julian Date = 0 on Janurar...
  ✓ JUL_EED -> jul_eed (0 enum values)
    Description: Estimated julian date of event start (Julian Date = 0 on Jan...
  ✓ JUL_LED -> jul_led (0 enum values)
    Description: Estimated julian date of event end (Julian Date = 0 on Janur...
  ✓ JUL_START_DATE -> jul_start_date (0 enum values)
    Description: Earliest start day of event (Julian Date = 0 on Janurary 1st...
  ✓ JUL_END_DATE -> jul_end_date (0 enum values)
    Description: Latest end day of event
  ✓ DAY_SPAN -> day_span (0 enum values)
    Description: Longest span of event, in days
  ✓ N_INJURD -> n_injurd (0 enum values)
    Description: # Of individuals injured
  ✓ TAR_GPOL -> tar_gpol (0 enum values)
    Description: Was the target a geo-political entity
  ✓ GP_TYPE -> gp_type (5 enum values)
    Description: Type of geo-political entity targeted
  ✓ aid -> aid (0 enum values)
    Description: Article id#
  ✓ PUB_MON -> pub_mon (0 enum values)
    Description: Global_pubdate_month
  ✓ PUB_DATE -> pub_date (0 enum values)
    Description: Global_pubdate_day
  ✓ PUB_YEAR -> pub_year (0 enum values)
    Description: Global_pubdate_year
  ✓ recap -> recap (0 enum values)
    Description: Is this a recapitulation coding?
  ✓ NEWS_SOURCE -> news_source (0 enum values)
    Description: Source of the coded article
  ✓ CODE_YEAR -> code_year (0 enum values)
    Description: Year of coding
  ✓ CODE_MONTH -> code_month (0 enum values)
    Description: Month of coding
  ✓ CODE_DAY -> code_day (0 enum values)
    Description: Day of coding
  ✓ event -> event (0 enum values)
    Description: Is this coding for a destabilizing event?
  ✓ posthoc -> posthoc (2 enum values)
    Description: Post hoc reaction?
  ✓ EV_TYPE -> ev_type (7 enum values)
    Description: Event type
  ✓ linked -> linked (0 enum values)
    Description: Is this a linked coding?
  ✓ LINK_TYPE -> link_type (2 enum values)
    Description: Type of event link
  ✓ FROM_EID -> from_eid (0 enum values)
    Description: Id of event linked from
  ✓ TO_EID -> to_eid (0 enum values)
    Description: Id of event linked to
  ✓ pinpoint -> pinpoint (0 enum values)
    Description: Type of geospatial data available
  ✓ GP3 -> gp3 (0 enum values)
    Description: Country name(caps and lower case)
  ✓ GP4 -> gp4 (0 enum values)
    Description: Lowest level entity name (caps and lower case)
  ✓ GP7 -> gp7 (0 enum values)
    Description: Latitude
  ✓ GP8 -> gp8 (0 enum values)
    Description: Longitude
  ✓ LOC_TYPE -> loc_type (29 enum values)
    Description: Event location type
  ✓ PE_TYPE -> pe_type (11 enum values)
    Description: Type of political expression event
  ✓ SYM_TYPE -> sym_type (15 enum values)
    Description: Type of symbolic event
  ✓ AD_VIOL -> ad_viol (4 enum values)
    Description: Were violent acts advocated?
  ✓ AD_TACT -> ad_tact (18 enum values)
    Description: Tactics advocated in political exp
  ✓ EXP_TYPE -> exp_type (4 enum values)
    Description: Reduced political expression type
  ✓ ATK_TYPE -> atk_type (23 enum values)
    Description: Type of political motivated attack
  ✓ DSA_TYPE -> dsa_type (5 enum values)
    Description: Broad category of disruptive state act
  ✓ STAT_ACT -> stat_act (57 enum values)
    Description: Type of disruptive state act
  ✓ N_OF_INI_P -> n_of_ini_p (0 enum values)
    Description: Pristine measure of # of initiators
  ✓ N_OF_INI_A -> n_of_ini_a (0 enum values)
    Description: Measure of # of initiators with statistical estimates
  ✓ WEAP_GRD -> weap_grd (0 enum values)
    Description: 5 category weapon variable
  ✓ N_KILLED_P -> n_killed_p (0 enum values)
    Description: Pristine estimate of # killed, from news report
  ✓ N_KILLED_A -> n_killed_a (0 enum values)
    Description: Estimate of # killed, including statistical estimates
  ✓ E_LENGTH -> e_length (4 enum values)
    Description: Length of event, truncated
  ✓ N_INJURD_D -> n_injurd_d (0 enum values)
    Description: # Injured, max=10
  ✓ DAM_PROP -> dam_prop (0 enum values)
    Description: Was property damaged in the event?
  ✓ arrests -> arrests (0 enum values)
    Description: Were arrests made?
  ✓ PER_ATK_I -> per_atk_i (0 enum values)
    Description: Integrated attack against a human variable
  ✓ PER_ATK_E -> per_atk_e (0 enum values)
    Description: Extraordinary violent attack against a human
  ✓ PUB_ORDER -> pub_order (0 enum values)
    Description: Event rooted in desire to maintain pub order?
  ✓ retribution -> retribution (0 enum values)
    Description: Event rooted in desire for retribution?
  ✓ POL_EXPRESS -> pol_express (0 enum values)
    Description: Intensity of small-bore political expression
  ✓ INTANG_REP -> intang_rep (0 enum values)
    Description: Level of intangible repression
  ✓ MASS_EXPRESS -> mass_express (0 enum values)
    Description: Intensity of mass expression
  ✓ POL_VIOL -> pol_viol (0 enum values)
    Description: Intensity of political violence
  ✓ STAT_VIOL -> stat_viol (0 enum values)
    Description: Intensity of state violence
  ✓ ST_REPRESS -> st_repress (0 enum values)
    Description: Intensity of tang state repression
  ✓ AMBIG_WGT -> ambig_wgt (0 enum values)
    Description: Weight to adjust for double counting initiators
  ✓ SC_ANIMOSITY -> sc_animosity (0 enum values)
    Description: Event rooted in socio-cultural animosities?
  ✓ ANTI_GOV_SENTMNTS -> anti_gov_sentmnts (0 enum values)
    Description: Event rooted in anti-government sentiments?
  ✓ CLASS_CONFLICT -> class_conflict (0 enum values)
    Description: Event rooted in class-based conflict?
  ✓ POL_DESIRES -> pol_desires (0 enum values)
    Description: Event rooted in desire for political rights?
  ✓ RETAIN_POWER -> retain_power (0 enum values)
    Description: Event rooted in desire to retain political power?
  ✓ ECO_SCARCITY -> eco_scarcity (0 enum values)
    Description: Event rooted in ecological resource scarcities
  ✓ PERS_SECURITY -> pers_security (0 enum values)
    Description: Event rooted in desire for personal security?
  ✓ QUASI_EVENT -> quasi_event (0 enum values)
    Description: Is this a quasi-event coding?
  ✓ coup -> coup (0 enum values)
    Description: Did this event involve a coup?
  ✓ COUP_FAILED -> coup_failed (0 enum values)
    Description: Did this event involve an unrealized coup?
  ✓ region -> region (8 enum values)
    Description: Eight category world region variable
  ✓ victim_effect -> victim_effect (13 enum values)
    Description: Impact of event on victim
  ✓ weapon -> weapon (27 enum values)
    Description: Type of weapon used
  ✓ property_damaged -> property_damaged (47 enum values)
    Description: Type of property damaged
  ✓ property_owner -> property_owner (12 enum values)
    Description: Type of owner for damaged property

## 7. Side-by-Side Comparison: Original vs Resolved Values

In [40]:
# Create a comparison view showing original and resolved values side by side
comparison_cols = []
for col in resolved_info.keys():
    comparison_cols.append(col)
    comparison_cols.append(f"{col}_resolved")

# Show comparison for columns that were resolved
if comparison_cols:
    comparison_df = resolved_df[comparison_cols]
    print("Side-by-Side Comparison (Original | Resolved):")
    print("=" * 100)
    display(comparison_df)
    
    # Also show a more detailed view for each resolved column
    print("\n\nDetailed View for Each Resolved Column:")
    print("=" * 100)
    for col in resolved_info.keys():
        print(f"\n{col}:")
        print("-" * 100)
        comparison = pd.DataFrame({
            'Original': resolved_df[col],
            'Resolved': resolved_df[f"{col}_resolved"]
        })
        display(comparison)
else:
    print("No columns were resolved. Check if column names in data match variable names in codebook.")

Side-by-Side Comparison (Original | Resolved):
====================================================================================================

,KNOW_INI,KNOW_INI_resolved,INI_TYPE,INI_TYPE_resolved,NGOV_I1,NGOV_I1_resolved,GOV_I1,GOV_I1_resolved,TAR_TYPE,TAR_TYPE_resolved,G_LVL_T,G_LVL_T_resolved,VIC_TYPE,VIC_TYPE_resolved,DATE_TYP,DATE_TYP_resolved,GP_TYPE,GP_TYPE_resolved,posthoc,posthoc_resolved,EV_TYPE,EV_TYPE_resolved,LINK_TYPE,LINK_TYPE_resolved,LOC_TYPE,LOC_TYPE_resolved,PE_TYPE,PE_TYPE_resolved,SYM_TYPE,SYM_TYPE_resolved,AD_VIOL,AD_VIOL_resolved,AD_TACT,AD_TACT_resolved,EXP_TYPE,EXP_TYPE_resolved,ATK_TYPE,ATK_TYPE_resolved,DSA_TYPE,DSA_TYPE_resolved,STAT_ACT,STAT_ACT_resolved,E_LENGTH,E_LENGTH_resolved,region,region_resolved,victim_effect,victim_effect_resolved,weapon,weapon_resolved,property_damaged,property_damaged_resolved,property_owner,property_owner_resolved
0,1.0,Initiator Known,1.0,Non Gov Initiator,22.0,Local Leader,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Human,NaN,NaN,NaN,NaN,0,No Post Hoc Reaction,1.0,Political Expression,NaN,NaN,27.0,Unspecified Location,4.0,Written,NaN,NaN,0,No Violence Advocated,17.0,None,1.0,Verbal or Written Expression,NaN,NaN,NaN,NaN,NaN,NaN,1,One Day,NaN,NaN,1.0,No Known Effects,1,No Weapon,NaN,NaN,NaN,NaN
1,1.0,Initiator Known,2.0,Gov Initiator,NaN,NaN,3.0,Soldier,3.0,Geo Pol Entity,NaN,NaN,NaN,NaN,NaN,NaN,5.0,Entire Nation,0,No Post Hoc Reaction,1.0,Political Expression,0.0,Part of,22.0,Military Facility,8.0,Job Action,NaN,NaN,0,No Violence Advocated,17.0,None,4.0,Mass Demonstration or Strike,NaN,NaN,NaN,NaN,NaN,NaN,1,One Day,NaN,NaN,NaN,NaN,1,No Weapon,NaN,NaN,NaN,NaN
2,1.0,Initiator Known,1.0,Non Gov Initiator,6.0,Worker,NaN,NaN,1.0,Human,3.0,National Government,NaN,NaN,1.0,Precise Single Day,NaN,NaN,0,No Post Hoc Reaction,1.0,Political Expression,NaN,NaN,2.0,Densely Populated Area,7.0,Demonstration/March,NaN,NaN,0,No Violence Advocated,17.0,None,4.0,Mass Demonstration or Strike,NaN,NaN,NaN,NaN,NaN,NaN,1,One Day,NaN,NaN,13.0,Some Other Effect,1,No Weapon,NaN,NaN,NaN,NaN
3,1.0,Initiator Known,1.0,Non Gov Initiator,5.0,Nondescript Individual,NaN,NaN,1.0,Human,3.0,National Government,NaN,NaN,1.0,Precise Single Day,NaN,NaN,0,No Post Hoc Reaction,1.0,Political Expression,NaN,NaN,2.0,Densely Populated Area,9.0,Symbolic Act,15.0,Other,0,No Violence Advocated,17.0,None,2.0,Symbolic Act,NaN,NaN,NaN,NaN,NaN,NaN,1,One Day,NaN,NaN,13.0,Some Other Effect,13,Non-lethal Projectiles,NaN,NaN,NaN,NaN
4,2.0,Ambiguous Initiator,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,Precise Single Day,NaN,NaN,0,No Post Hoc Reaction,2.0,Political Attacks,NaN,NaN,2.0,Densely Populated Area,NaN,NaN,NaN,NaN,0,No Violence Advocated,NaN,NaN,NaN,NaN,6.0,Other Personal Attack,NaN,NaN,NaN,NaN,1,One Day,NaN,NaN,13.0,Some Other Effect,1,No Weapon,NaN,NaN,NaN,NaN

Detailed View for Each Resolved Column:
====================================================================================================

KNOW_INI:
----------------------------------------------------------------------------------------------------

   Original             Resolved
0       1.0      Initiator Known
1       1.0      Initiator Known
2       1.0      Initiator Known
3       1.0      Initiator Known
4       2.0  Ambiguous Initiator

INI_TYPE:
----------------------------------------------------------------------------------------------------

   Original           Resolved
0       1.0  Non Gov Initiator
1       2.0      Gov Initiator
2       1.0  Non Gov Initiator
3       1.0  Non Gov Initiator
4       NaN                NaN

NGOV_I1:
----------------------------------------------------------------------------------------------------

   Original                Resolved
0      22.0            Local Leader
1       NaN                     NaN
2       6.0                  Worker
3       5.0  Nondescript Individual
4       NaN                     NaN

GOV_I1:
----------------------------------------------------------------------------------------------------

   Original Resolved
0       NaN      NaN
1       3.0  Soldier
2       NaN      NaN
3       NaN      NaN
4       NaN      NaN

TAR_TYPE:
----------------------------------------------------------------------------------------------------

   Original        Resolved
0       NaN             NaN
1       3.0  Geo Pol Entity
2       1.0           Human
3       1.0           Human
4       NaN             NaN

G_LVL_T:
----------------------------------------------------------------------------------------------------

   Original             Resolved
0       NaN                  NaN
1       NaN                  NaN
2       3.0  National Government
3       3.0  National Government
4       NaN                  NaN

VIC_TYPE:
----------------------------------------------------------------------------------------------------

   Original Resolved
0       1.0    Human
1       NaN      NaN
2       NaN      NaN
3       NaN      NaN
4       NaN      NaN

DATE_TYP:
----------------------------------------------------------------------------------------------------

   Original            Resolved
0       NaN                 NaN
1       NaN                 NaN
2       1.0  Precise Single Day
3       1.0  Precise Single Day
4       1.0  Precise Single Day

GP_TYPE:
----------------------------------------------------------------------------------------------------

   Original       Resolved
0       NaN            NaN
1       5.0  Entire Nation
2       NaN            NaN
3       NaN            NaN
4       NaN            NaN

posthoc:
----------------------------------------------------------------------------------------------------

   Original              Resolved
0         0  No Post Hoc Reaction
1         0  No Post Hoc Reaction
2         0  No Post Hoc Reaction
3         0  No Post Hoc Reaction
4         0  No Post Hoc Reaction

EV_TYPE:
----------------------------------------------------------------------------------------------------

   Original              Resolved
0       1.0  Political Expression
1       1.0  Political Expression
2       1.0  Political Expression
3       1.0  Political Expression
4       2.0     Political Attacks

LINK_TYPE:
----------------------------------------------------------------------------------------------------

   Original Resolved
0       NaN      NaN
1       0.0  Part of
2       NaN      NaN
3       NaN      NaN
4       NaN      NaN

LOC_TYPE:
----------------------------------------------------------------------------------------------------

   Original                Resolved
0      27.0    Unspecified Location
1      22.0       Military Facility
2       2.0  Densely Populated Area
3       2.0  Densely Populated Area
4       2.0  Densely Populated Area

PE_TYPE:
----------------------------------------------------------------------------------------------------

   Original             Resolved
0       4.0              Written
1       8.0           Job Action
2       7.0  Demonstration/March
3       9.0         Symbolic Act
4       NaN                  NaN

SYM_TYPE:
----------------------------------------------------------------------------------------------------

   Original Resolved
0       NaN      NaN
1       NaN      NaN
2       NaN      NaN
3      15.0    Other
4       NaN      NaN

AD_VIOL:
----------------------------------------------------------------------------------------------------

   Original               Resolved
0         0  No Violence Advocated
1         0  No Violence Advocated
2         0  No Violence Advocated
3         0  No Violence Advocated
4         0  No Violence Advocated

AD_TACT:
----------------------------------------------------------------------------------------------------

   Original Resolved
0      17.0     None
1      17.0     None
2      17.0     None
3      17.0     None
4       NaN      NaN

EXP_TYPE:
----------------------------------------------------------------------------------------------------

   Original                      Resolved
0       1.0  Verbal or Written Expression
1       4.0  Mass Demonstration or Strike
2       4.0  Mass Demonstration or Strike
3       2.0                  Symbolic Act
4       NaN                           NaN

ATK_TYPE:
----------------------------------------------------------------------------------------------------

   Original               Resolved
0       NaN                    NaN
1       NaN                    NaN
2       NaN                    NaN
3       NaN                    NaN
4       6.0  Other Personal Attack

DSA_TYPE:
----------------------------------------------------------------------------------------------------

   Original  Resolved
0       NaN       NaN
1       NaN       NaN
2       NaN       NaN
3       NaN       NaN
4       NaN       NaN

STAT_ACT:
----------------------------------------------------------------------------------------------------

   Original  Resolved
0       NaN       NaN
1       NaN       NaN
2       NaN       NaN
3       NaN       NaN
4       NaN       NaN

E_LENGTH:
----------------------------------------------------------------------------------------------------

   Original Resolved
0         1  One Day
1         1  One Day
2         1  One Day
3         1  One Day
4         1  One Day

region:
----------------------------------------------------------------------------------------------------

   Original  Resolved
0       NaN       NaN
1       NaN       NaN
2       NaN       NaN
3       NaN       NaN
4       NaN       NaN

victim_effect:
----------------------------------------------------------------------------------------------------

   Original           Resolved
0       1.0   No Known Effects
1       NaN                NaN
2      13.0  Some Other Effect
3      13.0  Some Other Effect
4      13.0  Some Other Effect

weapon:
----------------------------------------------------------------------------------------------------

   Original                Resolved
0         1               No Weapon
1         1               No Weapon
2         1               No Weapon
3        13  Non-lethal Projectiles
4         1               No Weapon

property_damaged:
----------------------------------------------------------------------------------------------------

   Original  Resolved
0       NaN       NaN
1       NaN       NaN
2       NaN       NaN
3       NaN       NaN
4       NaN       NaN

property_owner:
----------------------------------------------------------------------------------------------------

   Original  Resolved
0       NaN       NaN
1       NaN       NaN
2       NaN       NaN
3       NaN       NaN
4       NaN       NaN

## 8.1. Export with Replaced Values (Updated)

In [49]:
from datetime import datetime
import os

# Create output directory if it doesn't exist
output_dir = Path('output')
output_dir.mkdir(exist_ok=True)

# Generate filename with datetimestamp
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
output_filename = output_dir / f"resolved_data_{timestamp}.csv"

# Write resolved dataframe to CSV
# Replace original columns with resolved values (instead of having both)
if 'resolved_df' in locals() and not resolved_df.empty:
    # Create a copy of the resolved dataframe
    export_df = resolved_df.copy()
    
    # Replace original columns with resolved values
    for col in resolved_info.keys():
        resolved_col = f"{col}_resolved"
        if resolved_col in export_df.columns:
            # Replace the original column with resolved values
            export_df[col] = export_df[resolved_col]
            # Drop the _resolved column
            export_df = export_df.drop(columns=[resolved_col])
    
    # Rename columns to their descriptions from codebook
    column_rename_map = {}
    for col in export_df.columns:
        # Try to find matching variable in enum_mappings
        matching_var = None
        for var_name in enum_mappings.keys():
            if col.lower() == var_name.lower() or col.lower().replace('_', '') == var_name.lower().replace('_', ''):
                matching_var = var_name
                break
        
        if matching_var and enum_mappings[matching_var].get('description'):
            # Use the description as the new column name
            description = enum_mappings[matching_var]['description']
            # Clean up description for CSV column name (remove special chars, limit length)
            # Keep it readable but make it a valid column name
            clean_description = description.replace('\n', ' ').replace('\r', ' ').strip()
            # If description is too long, truncate it
            if len(clean_description) > 100:
                clean_description = clean_description[:97] + "..."
            column_rename_map[col] = clean_description
    
    # Apply the renaming
    if column_rename_map:
        export_df = export_df.rename(columns=column_rename_map)
    
    # Write to CSV
    export_df.to_csv(output_filename, index=False)
    print(f"✓ Resolved data exported successfully!")
    print(f"  File: {output_filename}")
    print(f"  Rows: {len(export_df):,}")
    print(f"  Columns: {len(export_df.columns)}")
    print(f"  Resolved columns: {len(resolved_info)}")
    print(f"  Note: Original enum values have been replaced with resolved text values")
    print(f"  Note: Column names have been replaced with their descriptions from codebook")
    
    # Also create a summary file
    summary_filename = output_dir / f"resolution_summary_{timestamp}.txt"
    with open(summary_filename, 'w') as f:
        f.write(f"SPEED Dataset - Enum Resolution Summary\n")
        f.write(f"{'='*80}\n\n")
        f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Source data: {data_file}\n")
        f.write(f"Codebook: {codebook_file}\n\n")
        f.write(f"Dataset Summary:\n")
        f.write(f"  Total rows in dataset: {len(df):,}\n")
        f.write(f"  Sample rows exported: {len(export_df):,}\n")
        f.write(f"  Total columns: {len(df.columns)}\n")
        f.write(f"  Columns with enum mappings: {len(resolved_info)}\n")
        f.write(f"  Note: Original enum values have been replaced with resolved text values\n")
        f.write(f"  Note: Column names have been replaced with their descriptions from codebook\n\n")
        f.write(f"Resolved Columns:\n")
        f.write(f"{'-'*80}\n")
        for col, info in resolved_info.items():
            f.write(f"\n{col}:\n")
            f.write(f"  Mapping Variable: {info['mapping_var']}\n")
            if info.get('description'):
                f.write(f"  Description: {info['description']}\n")
            f.write(f"  Unique values in sample: {len(info['unique_values'])}\n")
            if enum_mappings[info['mapping_var']].get('enums'):
                enum_count = len(enum_mappings[info['mapping_var']]['enums'])
                f.write(f"  Total enum values in codebook: {enum_count}\n")
    
    print(f"✓ Summary file created: {summary_filename}")
else:
    print("⚠ No resolved data available to export. Run the previous cells first.")

✓ Resolved data exported successfully!
  File: output/resolved_data_20260121_152103.csv
  Rows: 62,141
  Columns: 106
  Resolved columns: 27
  Note: Original enum values have been replaced with resolved text values
  Note: Column names have been replaced with their descriptions from codebook
✓ Summary file created: output/resolution_summary_20260121_152103.txt

## 8. Export Resolved Data to CSV

In [41]:
from datetime import datetime
import os

# Create output directory if it doesn't exist
output_dir = Path('output')
output_dir.mkdir(exist_ok=True)

# Generate filename with datetimestamp
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
output_filename = output_dir / f"resolved_data_{timestamp}.csv"

# Write resolved dataframe to CSV
# Include both original and resolved columns
if 'resolved_df' in locals() and not resolved_df.empty:
    resolved_df.to_csv(output_filename, index=False)
    print(f"✓ Resolved data exported successfully!")
    print(f"  File: {output_filename}")
    print(f"  Rows: {len(resolved_df):,}")
    print(f"  Columns: {len(resolved_df.columns)}")
    print(f"  Resolved columns: {len(resolved_info)}")
    
    # Also create a summary file
    summary_filename = output_dir / f"resolution_summary_{timestamp}.txt"
    with open(summary_filename, 'w') as f:
        f.write(f"SPEED Dataset - Enum Resolution Summary\n")
        f.write(f"{'='*80}\n\n")
        f.write(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Source data: {data_file}\n")
        f.write(f"Codebook: {codebook_file}\n\n")
        f.write(f"Dataset Summary:\n")
        f.write(f"  Total rows in dataset: {len(df):,}\n")
        f.write(f"  Sample rows exported: {len(resolved_df):,}\n")
        f.write(f"  Total columns: {len(df.columns)}\n")
        f.write(f"  Columns with enum mappings: {len(resolved_info)}\n\n")
        f.write(f"Resolved Columns:\n")
        f.write(f"{'-'*80}\n")
        for col, info in resolved_info.items():
            f.write(f"\n{col}:\n")
            f.write(f"  Mapping Variable: {info['mapping_var']}\n")
            if info.get('description'):
                f.write(f"  Description: {info['description']}\n")
            f.write(f"  Unique values in sample: {len(info['unique_values'])}\n")
            if enum_mappings[info['mapping_var']].get('enums'):
                enum_count = len(enum_mappings[info['mapping_var']]['enums'])
                f.write(f"  Total enum values in codebook: {enum_count}\n")
    
    print(f"✓ Summary file created: {summary_filename}")
else:
    print("⚠ No resolved data available to export. Run the previous cells first.")

✓ Resolved data exported successfully!
  File: output/resolved_data_20260121_145130.csv
  Rows: 5
  Columns: 133
  Resolved columns: 27
✓ Summary file created: output/resolution_summary_20260121_145130.txt